#include "doctest.h"
#include "Position.hpp"
#include "Figure.hpp"
#include "FigureKeeper.hpp"
#include "Evaluate.hpp"
#include "Game.hpp"
#include "TestBotFactory.hpp"
#include "AlphaBetaBot.hpp"

#include <vector>
#include <memory>
#include <iostream>

using std::cout;
using std::endl;


TEST_CASE("Test hash adding")
{
    std::vector<std::pair<Position, Figure>> v;
    std::vector<std::pair<Position, Figure>> adding
    {
        {Position(1, 2, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)},
        {Position(1, 2, 4), Figure(PlayerColour::white_, FigureType::DOMINATOR)},
        {Position(1, 2, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)},
        {Position(1, 2, 6), Figure(PlayerColour::white_, FigureType::DEFENSSOR)},
        {Position(1, 2, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)},
        {Position(1, 2, 8), Figure(PlayerColour::white_, FigureType::PROGRESSOR)},

        {Position(2, 2, 3), Figure(PlayerColour::black_, FigureType::INTELLECTOR)},
        {Position(3, 2, 4), Figure(PlayerColour::black_, FigureType::DOMINATOR)},
        {Position(4, 2, 5), Figure(PlayerColour::black_, FigureType::AGGRESSOR)},
        {Position(5, 2, 6), Figure(PlayerColour::black_, FigureType::DEFENSSOR)},
        {Position(6, 2, 7), Figure(PlayerColour::black_, FigureType::LIBERATOR)},
        {Position(7, 2, 8), Figure(PlayerColour::black_, FigureType::PROGRESSOR)}

    };


    FigureKeeper fk{};  

    for(auto i : adding)
    {
        fk.insertFigure(i.first, i.second);
        v.push_back(i);
        FigureKeeper temp(v);
        CHECK(temp.get_hash() == fk.get_hash());
    }
}

struct Action
{
    bool type_; //0 - Erase, 1 - Insert
    Position pos_;
    Figure fig_;

    Action(bool type, Position pos, Figure fig) : type_(type), pos_(pos), fig_(fig) {}; 
};

static std::unordered_map<PlayerColour, int> colour_val = 
{
    {PlayerColour::white_, 0},
    {PlayerColour::black_, 1}
};

static std::unordered_map<FigureType, int> type_val = 
{
    {FigureType::INTELLECTOR, 0},
    {FigureType::DOMINATOR, 0},
    {FigureType::AGGRESSOR, 0},
    {FigureType::DEFENSSOR, 0},
    {FigureType::LIBERATOR, 0},
    {FigureType::PROGRESSOR, 0}
};

bool operator<(const Action &a, const Action &b) 
{
    return std::make_tuple(a.type_, a.pos_.posW(), a.pos_.posH(), colour_val[a.fig_.colour_], type_val[a.fig_.type_]) <
           std::make_tuple(b.type_, b.pos_.posW(), b.pos_.posH(), colour_val[b.fig_.colour_], type_val[b.fig_.type_]); 
}

TEST_CASE("Insert and erase")
{
    std::vector<Action> actions =
    {
        Action(1, Position(1, 2, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(1, 2, 4), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(1, 2, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(1, 2, 6), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(1, 2, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(1, 2, 8), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),

        Action(1, Position(2, 2, 3), Figure(PlayerColour::black_, FigureType::INTELLECTOR)),
        Action(1, Position(3, 2, 4), Figure(PlayerColour::black_, FigureType::DOMINATOR)),
        Action(1, Position(4, 2, 5), Figure(PlayerColour::black_, FigureType::AGGRESSOR)),
        Action(1, Position(5, 2, 6), Figure(PlayerColour::black_, FigureType::DEFENSSOR)),
        Action(1, Position(6, 2, 7), Figure(PlayerColour::black_, FigureType::LIBERATOR)),
        Action(1, Position(7, 2, 8), Figure(PlayerColour::black_, FigureType::PROGRESSOR)),

        Action(0, Position(1, 2, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(1, 2, 4), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(1, 2, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(1, 2, 6), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(1, 2, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(1, 2, 8), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),

        Action(0, Position(2, 2, 3), Figure(PlayerColour::black_, FigureType::INTELLECTOR)),
        Action(0, Position(3, 2, 4), Figure(PlayerColour::black_, FigureType::DOMINATOR)),
        Action(0, Position(4, 2, 5), Figure(PlayerColour::black_, FigureType::AGGRESSOR)),
        Action(0, Position(5, 2, 6), Figure(PlayerColour::black_, FigureType::DEFENSSOR)),
        Action(0, Position(6, 2, 7), Figure(PlayerColour::black_, FigureType::LIBERATOR)),
        Action(0, Position(7, 2, 8), Figure(PlayerColour::black_, FigureType::PROGRESSOR)),
    };

    FigureKeeper fk{};

    std::set<Action> current;

    for(auto i : actions)
    {
        if(i.type_ == 0)
        {
            current.erase(Action(0, i.pos_, i.fig_));
            fk.eraseFigure(i.pos_, i.fig_);
        }
        else
        {
            current.insert(Action(0, i.pos_, i.fig_));
            fk.insertFigure(i.pos_, i.fig_);
        }

        std::vector<std::pair<Position, Figure>> tmp_v;
        for(auto &j : current)
            tmp_v.push_back({j.pos_, j.fig_});

        FigureKeeper tmp(tmp_v);

        CHECK(fk == tmp);
    }
}

TEST_CASE("1000 cases")
{
    std::vector<Action> actions =
    {
        Action(1, Position(57, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(57, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(10, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(20, 97), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(38, 51), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(20, 97), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(10, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(50, 82), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(55, 89), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(38, 51), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(29, 39), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(55, 89), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(50, 82), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(68, 73), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(3, 73), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(3, 73), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(18, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(93, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(86, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(68, 73), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(16, 55), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(74, 47), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(16, 55), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(86, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(79, 42), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(79, 42), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(61, 26), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(69, 79), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(69, 41), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(61, 26), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(91, 29), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(84, 3), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(69, 41), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(26, 29), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(63, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(62, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(63, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(1, 42), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(29, 39), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(89, 2), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(93, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(80, 23), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(80, 23), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(1, 75), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(51, 31), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(84, 3), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(69, 79), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(91, 29), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(1, 42), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(62, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(51, 31), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(99, 75), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(15, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(74, 47), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(18, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(15, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(93, 56), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(15, 51), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(60, 69), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(60, 69), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(15, 51), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(20, 34), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(99, 75), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(93, 56), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(72, 65), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(57, 27), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(49, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(26, 29), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(57, 27), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(1, 75), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(89, 2), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(72, 65), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(20, 34), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(52, 50), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(49, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(48, 34), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(14, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(45, 20), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(68, 30), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(52, 49), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(53, 51), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(69, 1), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(52, 49), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(68, 30), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(14, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(45, 20), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(97, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(48, 34), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(26, 73), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(53, 51), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(60, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(97, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(64, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(64, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(60, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(26, 73), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(52, 50), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(83, 10), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(69, 1), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(84, 39), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(83, 10), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(84, 39), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(41, 46), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(41, 46), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(76, 62), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(76, 62), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(50, 77), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(92, 93), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(50, 77), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(92, 93), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(29, 95), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(29, 95), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(67, 25), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(67, 25), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(19, 64), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(92, 29), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(92, 29), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(16, 14), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(19, 64), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(16, 14), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(21, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(20, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(24, 63), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(21, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(50, 83), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(50, 83), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(24, 63), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(10, 95), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(20, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(65, 0), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(65, 0), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(39, 22), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(39, 22), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(10, 95), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(63, 7), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(64, 27), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(63, 7), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(73, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(52, 5), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(89, 77), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(64, 27), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(59, 0), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(88, 8), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(73, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(52, 5), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(87, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(30, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(88, 8), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(67, 88), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(60, 28), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(9, 82), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(67, 88), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(84, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(84, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(89, 77), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(99, 14), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(99, 14), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(14, 18), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(87, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(77, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(37, 0), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(48, 84), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(81, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(46, 32), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(48, 84), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(14, 18), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(9, 82), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(35, 39), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(60, 28), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(59, 0), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(46, 32), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(37, 0), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(81, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(21, 38), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(35, 39), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(2, 87), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(30, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(82, 9), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(72, 44), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(58, 51), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(82, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(62, 1), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(4, 40), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(78, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(95, 14), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(58, 51), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(65, 25), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(72, 26), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(20, 69), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(3, 82), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(77, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(20, 69), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(70, 62), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(7, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(87, 77), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(12, 6), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(70, 62), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(3, 82), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(3, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(7, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(57, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(27, 46), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(28, 16), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(98, 37), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(72, 44), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(33, 82), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(18, 98), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(33, 5), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(72, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(62, 1), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(28, 16), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(8, 63), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(94, 26), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(2, 87), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(82, 9), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(97, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(62, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(4, 40), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(98, 37), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(57, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(82, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(25, 6), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(70, 83), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(94, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(94, 26), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(65, 25), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(87, 77), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(62, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(52, 45), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(18, 98), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(7, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(12, 6), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(98, 92), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(72, 26), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(28, 1), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(72, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(10, 38), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(25, 6), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(33, 5), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(63, 30), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(55, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(39, 99), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(3, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(7, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(8, 63), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(78, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(95, 14), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(39, 6), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(20, 63), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(89, 68), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(39, 45), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(61, 35), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(93, 44), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(27, 78), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(78, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(0, 84), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(77, 88), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(0, 84), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(74, 86), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(34, 39), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(27, 78), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(54, 57), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(34, 39), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(57, 16), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(39, 6), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(20, 63), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(65, 37), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(81, 9), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(27, 46), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(41, 10), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(97, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(39, 99), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(77, 88), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(94, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(21, 38), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(22, 92), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(70, 83), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(61, 35), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(93, 44), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(89, 68), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(84, 87), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(54, 57), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(32, 55), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(84, 87), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(37, 70), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(44, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(8, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(8, 12), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(57, 16), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(78, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(85, 89), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(41, 10), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(63, 30), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(58, 91), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(21, 41), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(47, 88), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(86, 55), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(85, 89), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(74, 86), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(4, 9), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(47, 88), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(98, 92), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(37, 42), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(8, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(33, 82), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(39, 45), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(81, 9), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(58, 91), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(65, 37), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(54, 2), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(37, 70), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(28, 1), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(55, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(24, 60), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(37, 42), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(52, 45), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(96, 38), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(83, 44), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(21, 41), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(44, 7), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(35, 0), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(54, 2), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(47, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(27, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(83, 88), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(10, 38), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(60, 34), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(32, 55), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(93, 17), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(44, 27), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(36, 95), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(47, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(64, 87), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(22, 92), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(97, 2), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(15, 11), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(86, 55), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(83, 44), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(49, 32), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(89, 50), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(24, 60), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(36, 95), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(64, 87), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(85, 18), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(11, 2), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(77, 22), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(31, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(97, 2), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(95, 8), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(85, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(26, 17), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(49, 32), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(27, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(68, 22), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(44, 27), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(95, 8), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(53, 35), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(83, 88), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(93, 17), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(96, 38), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(72, 24), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(85, 87), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(8, 48), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(90, 31), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(53, 35), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(85, 87), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(70, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(3, 23), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(72, 24), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(85, 40), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(15, 11), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(11, 2), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(8, 93), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(77, 22), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(4, 9), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(49, 66), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(96, 74), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(60, 34), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(91, 74), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(14, 8), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(3, 23), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(25, 41), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(91, 74), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(49, 66), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(85, 18), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(70, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(57, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(25, 41), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(70, 57), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(90, 31), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(50, 13), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(46, 37), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(83, 64), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(8, 93), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(57, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(29, 33), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(31, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(60, 48), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(33, 8), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(46, 37), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(36, 20), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(8, 12), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(63, 88), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(8, 0), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(48, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(14, 8), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(8, 48), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(49, 91), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(83, 64), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(14, 9), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(33, 8), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(14, 9), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(49, 91), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(36, 20), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(99, 83), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(35, 0), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(8, 0), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(32, 11), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(68, 22), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(29, 33), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(70, 57), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(81, 17), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(60, 48), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(50, 13), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(96, 74), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(44, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(16, 87), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(89, 50), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(90, 15), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(78, 36), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(77, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(48, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(16, 87), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(68, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(32, 11), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(89, 48), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(81, 17), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(7, 96), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(20, 14), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(7, 96), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(90, 15), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(89, 48), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(26, 17), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(95, 76), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(99, 83), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(63, 88), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(77, 34), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(20, 14), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(78, 36), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(15, 29), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(44, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(15, 29), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(95, 76), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(68, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(29, 90), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(0, 77), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(29, 90), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(0, 77), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(89, 56), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(89, 56), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(19, 75), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(19, 75), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(15, 50), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(38, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(15, 50), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(96, 69), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(87, 95), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(87, 95), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(38, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(47, 75), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(15, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(47, 75), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(96, 69), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(15, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(29, 6), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(29, 6), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(8, 73), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(8, 73), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(9, 35), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(11, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(9, 35), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(98, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(98, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(11, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(0, 13), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(21, 31), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(19, 90), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(0, 13), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(42, 92), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(97, 87), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(42, 92), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(80, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(44, 74), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(44, 74), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(83, 33), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(19, 90), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(80, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(87, 7), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(97, 87), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(21, 31), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(83, 33), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(87, 7), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(19, 71), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(19, 71), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(13, 50), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(49, 62), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(84, 86), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(19, 5), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(94, 99), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(32, 75), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(35, 51), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(84, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(34, 38), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(78, 43), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(76, 42), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(77, 2), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(49, 62), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(15, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(78, 43), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(90, 46), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(32, 83), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(56, 24), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(84, 86), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(0, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(33, 55), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(74, 93), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(15, 64), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(5, 47), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(63, 47), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(32, 83), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(15, 64), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(32, 75), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(87, 91), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(79, 11), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(74, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(63, 47), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(70, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(71, 64), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(13, 50), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(35, 26), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(94, 99), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(15, 96), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(14, 69), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(15, 96), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(67, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(39, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(17, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(88, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(47, 16), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(71, 64), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(17, 89), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(17, 89), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(47, 16), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(32, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(62, 44), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(5, 47), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(74, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(55, 28), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(14, 69), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(19, 5), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(38, 82), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(79, 11), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(33, 55), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(30, 23), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(28, 30), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(16, 67), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(77, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(14, 41), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(84, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(16, 67), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(35, 51), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(77, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(9, 81), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(89, 47), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(38, 82), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(67, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(92, 41), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(43, 8), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(90, 46), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(77, 2), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(30, 23), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(37, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(80, 91), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(78, 72), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(80, 91), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(71, 68), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(37, 28), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(57, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(90, 64), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(87, 53), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(74, 93), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(89, 47), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(46, 31), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(77, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(76, 42), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(14, 41), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(35, 26), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(0, 66), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(90, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(70, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(19, 88), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(75, 67), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(45, 47), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(37, 56), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(40, 67), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(40, 67), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(31, 42), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(31, 42), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(46, 31), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(95, 12), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(39, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(56, 24), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(74, 53), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(95, 12), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(47, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(34, 38), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(61, 31), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(9, 81), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(0, 59), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(34, 62), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(92, 1), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(75, 67), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(87, 91), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(15, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(17, 79), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(90, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(37, 11), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(30, 24), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(53, 78), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(46, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(0, 66), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(87, 53), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(30, 13), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(55, 28), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(28, 30), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(32, 65), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(58, 84), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(45, 5), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(57, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(47, 95), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(59, 37), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(74, 53), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(15, 65), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(62, 44), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(12, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(32, 65), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(88, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(61, 31), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(30, 13), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(54, 88), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(5, 0), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(62, 38), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(22, 13), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(71, 35), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(52, 38), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(58, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(45, 5), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(36, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(46, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(25, 65), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(90, 64), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(65, 87), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(62, 38), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(43, 8), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(32, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(45, 47), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(83, 20), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(12, 78), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(2, 69), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(56, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(58, 75), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(59, 37), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(53, 78), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(94, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(37, 28), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(54, 17), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(36, 34), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(10, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(92, 1), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(54, 17), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(77, 36), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(71, 35), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(30, 24), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(55, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(48, 74), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(68, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(23, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(94, 61), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(30, 93), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(2, 69), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(24, 2), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(25, 65), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(54, 88), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(22, 52), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(65, 87), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(75, 96), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(9, 76), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(98, 20), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(84, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(55, 1), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(19, 88), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(19, 49), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(31, 45), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(84, 95), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(68, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(21, 41), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(58, 84), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(87, 27), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(27, 0), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(77, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(79, 87), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(99, 39), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(24, 2), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(52, 38), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(83, 20), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(56, 44), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(21, 41), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(22, 58), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(23, 54), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(12, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(31, 45), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(37, 60), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(66, 65), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(15, 65), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(14, 37), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(21, 31), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(63, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(79, 87), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(79, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(22, 52), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(39, 89), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(78, 72), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(34, 62), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(39, 89), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(23, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(38, 23), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(19, 49), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(97, 60), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(97, 60), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(14, 37), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(92, 41), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(23, 52), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(38, 23), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(23, 37), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(99, 39), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(23, 54), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(5, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(55, 76), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(11, 6), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(75, 96), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(10, 19), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(15, 27), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(50, 94), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(99, 71), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(55, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(21, 31), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(10, 19), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(66, 65), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(55, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(48, 74), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(94, 82), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(96, 10), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(22, 58), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(76, 37), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(51, 49), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(5, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(34, 51), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(63, 45), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(94, 82), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(37, 58), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(85, 38), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(15, 27), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(63, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(37, 56), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(2, 80), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(79, 61), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(93, 60), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(43, 18), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(93, 60), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(60, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(60, 10), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(9, 76), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(66, 86), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(98, 20), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(64, 45), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(68, 56), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(29, 73), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(86, 74), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(22, 41), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(22, 41), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(51, 65), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(42, 12), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(86, 25), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(87, 27), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(51, 49), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(60, 10), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(85, 38), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(43, 48), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(68, 8), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(5, 0), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(86, 25), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(21, 77), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(51, 87), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(63, 45), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(56, 94), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(43, 48), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(67, 4), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(53, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(49, 22), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(55, 76), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(24, 53), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(30, 93), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(30, 72), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(6, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(47, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(32, 29), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(12, 78), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(5, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(42, 12), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(2, 80), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(43, 43), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(64, 45), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(6, 3), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(86, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(56, 94), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(29, 73), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(38, 91), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(67, 4), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(81, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(1, 77), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(35, 52), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(84, 95), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(22, 13), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(96, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(65, 57), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(10, 64), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(74, 42), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(33, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(68, 56), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(49, 22), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(51, 87), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(60, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(38, 91), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(86, 74), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(74, 42), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(26, 49), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(84, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(51, 65), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(52, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(5, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(58, 75), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(40, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(6, 66), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(53, 56), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(32, 29), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(30, 72), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(0, 52), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(88, 84), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(60, 51), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(44, 37), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(44, 35), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(76, 4), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(58, 75), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(37, 60), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(56, 37), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(35, 21), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(6, 51), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(76, 37), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(52, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(88, 84), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(35, 52), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(86, 32), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(6, 66), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(4, 61), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(95, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(86, 13), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(66, 86), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(81, 5), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(68, 8), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(71, 68), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(2, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(69, 55), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(27, 52), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(26, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(74, 35), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(84, 31), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(47, 79), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(24, 29), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(76, 4), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(89, 72), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(11, 6), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(26, 12), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(21, 28), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(44, 37), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(69, 55), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(56, 4), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(60, 5), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(40, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(1, 77), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(99, 71), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(50, 71), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(32, 86), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(32, 86), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(96, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(35, 21), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(47, 80), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(83, 64), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(4, 61), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(9, 52), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(26, 49), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(21, 28), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(50, 94), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(24, 53), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(73, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(46, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(47, 80), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(15, 47), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(27, 52), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(87, 25), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(12, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(34, 3), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(89, 81), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(39, 8), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(33, 35), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(40, 55), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(83, 64), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(60, 51), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(12, 36), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(12, 46), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(73, 37), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(10, 20), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(73, 37), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(21, 77), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(34, 51), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(54, 13), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(89, 72), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(26, 12), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(14, 67), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(0, 52), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(86, 13), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(77, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(12, 36), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(73, 90), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(75, 41), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(45, 96), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(86, 43), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(2, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(83, 66), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(65, 57), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(86, 43), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(26, 67), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(55, 18), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(72, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(96, 10), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(24, 29), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(16, 88), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(46, 15), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(16, 62), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(88, 77), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(92, 48), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(83, 68), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(43, 18), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(95, 66), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(1, Position(54, 70), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(88, 77), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(32, 96), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(72, 62), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(68, 58), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(32, 96), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(39, 88), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(27, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(14, 90), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(23, 97), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(1, Position(67, 3), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(77, 32), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(92, 48), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(77, 98), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(27, 92), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(56, 4), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(19, 6), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(88, 47), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(8, 64), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(30, 61), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(43, 39), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(98, 18), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(0, Position(19, 6), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(54, 13), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(0, Position(9, 52), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(88, 47), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(59, 30), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(54, 14), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(1, Position(18, 3), Figure(PlayerColour::white_, FigureType::PROGRESSOR)),
        Action(1, Position(93, 10), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(0, Position(59, 30), Figure(PlayerColour::white_, FigureType::AGGRESSOR)),
        Action(1, Position(41, 16), Figure(PlayerColour::white_, FigureType::DEFENSSOR)),
        Action(0, Position(44, 35), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(83, 66), Figure(PlayerColour::white_, FigureType::LIBERATOR)),
        Action(0, Position(56, 37), Figure(PlayerColour::white_, FigureType::DOMINATOR)),
        Action(1, Position(57, 23), Figure(PlayerColour::white_, FigureType::INTELLECTOR)),
        Action(0, Position(10, 64), Figure(PlayerColour::white_, FigureType::DOMINATOR)),

    };

    FigureKeeper fk{};

    std::set<Action> current;

    for(auto i : actions)
    {
        if(i.type_ == 0)
        {
            current.erase(Action(0, i.pos_, i.fig_));
            fk.eraseFigure(i.pos_, i.fig_);
        }
        else
        {
            current.insert(Action(0, i.pos_, i.fig_));
            fk.insertFigure(i.pos_, i.fig_);
        }

        std::vector<std::pair<Position, Figure>> tmp_v;
        for(auto &j : current)
            tmp_v.push_back({j.pos_, j.fig_});

        FigureKeeper tmp(tmp_v);

        CHECK(fk == tmp);
    }
}

TEST_CASE("Game with depth 2")
{
    const int depth = 1;
    std::shared_ptr<AlphaBetaBot> bot = std::reinterpret_pointer_cast<AlphaBetaBot>(TestBotFactory(2, depth));
    Game game{};

    int cnt = 0;
    for(;game.getGameStatus() == GameStatus::game_running_;)
    {
        auto move = bot->makeMove(game);

        game.makeMove(move);

        FigureKeeper tmp(game.getBoard());
        cnt++;

        bot->makeMove(game);

        CHECK(tmp == bot->getFigures());
        if(!(tmp == bot->getFigures()))
        {
            cout << cnt << endl;
            cout << tmp.get_figures(PlayerColour::white_).size() << ' ' << tmp.get_figures(PlayerColour::black_).size() << endl;
        }
    }
    cout << "Game with depth 2 passed." << endl;

}

TEST_CASE("Game with depth 3")
{
    const int depth = 2;
    std::shared_ptr<AlphaBetaBot> bot = std::reinterpret_pointer_cast<AlphaBetaBot>(TestBotFactory(2, depth));
    Game game{};

    int cnt = 0;
    for(;game.getGameStatus() == GameStatus::game_running_;)
    {
        auto move = bot->makeMove(game);

        game.makeMove(move);

        FigureKeeper tmp(game.getBoard());
        cnt++;

        bot->makeMove(game);

        CHECK(tmp == bot->getFigures());
        if(!(tmp == bot->getFigures()))
        {
            cout << cnt << endl;
            cout << tmp.get_figures(PlayerColour::white_).size() << ' ' << tmp.get_figures(PlayerColour::black_).size() << endl;
        }
    }
    cout << "Game with depth 3 passed." << endl;

}

TEST_CASE("Game with depth 4")
{
    const int depth = 3;
    std::shared_ptr<AlphaBetaBot> bot = std::reinterpret_pointer_cast<AlphaBetaBot>(TestBotFactory(2, depth));
    Game game{};

    int cnt = 0;
    for(;game.getGameStatus() == GameStatus::game_running_;)
    {
        auto move = bot->makeMove(game);

        game.makeMove(move);

        FigureKeeper tmp(game.getBoard());
        cnt++;

        bot->makeMove(game);

        CHECK(tmp == bot->getFigures());
        if(!(tmp == bot->getFigures()))
        {
            cout << cnt << endl;
            cout << tmp.get_figures(PlayerColour::white_).size() << ' ' << tmp.get_figures(PlayerColour::black_).size() << endl;
        }
    }
    cout << "Game with depth 4 passed." << endl;


}

// TEST_CASE("Game with depth 5")
// {
//     const int depth = 4;
//     std::shared_ptr<AlphaBetaBot> bot = std::reinterpret_pointer_cast<AlphaBetaBot>(TestBotFactory(2, depth));
//     Game game{};

//     int cnt = 0;
//     for(;game.getGameStatus() == GameStatus::game_running_;)
//     {
//         auto move = bot->makeMove(game);

//         game.makeMove(move);

//         FigureKeeper tmp(game.getBoard());
//         cnt++;

//         bot->makeMove(game);

//         CHECK(tmp == bot->getFigures());
//         if(!(tmp == bot->getFigures()))
//         {
//             cout << cnt << endl;
//             cout << tmp.get_figures(PlayerColour::white_).size() << ' ' << tmp.get_figures(PlayerColour::black_).size() << endl;
//         }
//     }
//     cout << "Game with depth 5 passed." << endl;

// }



