#ifndef _VIEW_MENU_TYPES_HPP_
#define _VIEW_MENU_TYPES_HPP_

namespace viewCurses {

enum class MENU_TYPE { BASE_MENU, WELCOME_MENU, MAIN_MENU, GAME_MENU, OPTIONS_MENU, MULTIPLEXER_MENU };

}

#endif
